---
# This file is centrally managed in https://github.com/<organization>/.github/
# Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in
# the above-mentioned repo.

blank_issues_enabled: false
contact_links:
  - name: Docs
    url: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide
    about: Setup guide and documentation
  - name: Support
    url: https://moonlight-stream.org/discord
    about: Official Moonlight support
  - name: Feature request
    url: https://ideas.moonlight-stream.org/
    about: Share your suggestions or ideas to help us improve
